#!/usr/bin/env bash
#
# lain installer — builds the monorepo and puts a `lain` launcher on your PATH.
#
#   curl-free: clone the repo, then run `bash install.sh`
#   Re-runnable and idempotent. Never touches your explorations (.db) or config.
#
# Env:
#   LAIN_BIN_DIR   where to put the launcher (default: ~/.local/bin)
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${LAIN_BIN_DIR:-$HOME/.local/bin}"

echo "lain installer"
echo "  repo: $REPO"
echo "  bin:  $BIN_DIR"
echo

# --- prerequisites -----------------------------------------------------------
if ! command -v bun >/dev/null 2>&1; then
  echo "✗ bun is required. Install it: https://bun.sh  (curl -fsSL https://bun.sh/install | bash)" >&2
  exit 1
fi
if ! command -v pnpm >/dev/null 2>&1; then
  echo "✗ pnpm is required. Install it: https://pnpm.io  (npm i -g pnpm, or: corepack enable)" >&2
  exit 1
fi
echo "✓ bun $(bun --version)   ✓ pnpm $(pnpm --version)"

# --- build -------------------------------------------------------------------
echo
echo "Installing dependencies..."
pnpm install --dir "$REPO" >/dev/null 2>&1 || (cd "$REPO" && pnpm install)
echo "Building all packages..."
(cd "$REPO" && pnpm build)

# --- launcher ----------------------------------------------------------------
mkdir -p "$BIN_DIR"
LAUNCHER="$BIN_DIR/lain"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# lain launcher (generated by install.sh) — runs the CLI from the source checkout.
exec bun "$REPO/packages/cli/dist/index.js" "\$@"
EOF
chmod +x "$LAUNCHER"
echo
echo "✓ Installed launcher → $LAUNCHER"

# --- PATH check --------------------------------------------------------------
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    echo
    echo "⚠ $BIN_DIR is not on your PATH. Add this to your shell rc:"
    echo "    export PATH=\"$BIN_DIR:\$PATH\""
    ;;
esac

echo
echo "Done. Next:"
echo "    lain init                 # configure your provider + key"
echo "    lain \"a city that dreams\" --mission   # your first exploration"
echo "    lain doctor               # verify everything"
